### ISSUE TITLE
Can't convert to color exception when API < 21

### ISSUE THREAD

**Issue by JairAviles** [julianfalcionelli/MagicForm#6]
According to the following [issue](https://stackoverflow.com/questions/27986204/cant-convert-to-color-type-0x2-error-when-inflating-layout-in-fragment-but-onl) on stackoverflow, it is occurring the same exception when implementing the MagicForm plugin and testing in a device with an API lesser than 21.

I am copying the following stack trace. Works fine on newer API versions, though.

`java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                                                              at android.content.res.TypedArray.getColor(TypedArray.java:326)
                                                                              at android.widget.TextView.<init>(TextView.java:499)
                                                                              at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
                                                                              at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
                                                                              at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:54)
                                                                              at android.support.design.widget.TextInputLayout.setErrorEnabled(TextInputLayout.java:602)
                                                                              at julianfalcionelli.magicform.helper.ValidationHelper.setError(ValidationHelper.java:67)
                                                                              at julianfalcionelli.magicform.helper.ValidationHelper.setError(ValidationHelper.java:50)
                                                                              at julianfalcionelli.magicform.MagicForm.checkField(MagicForm.java:168)
                                                                              at julianfalcionelli.magicform.MagicForm.checkField(MagicForm.java:135)
                                                                              at julianfalcionelli.magicform.MagicForm.validate(MagicForm.java:51)
                                                                              at br.com.ahgora.ahgoraexpo.surface.DrawResults$1.onClick(MyAppActivity.java:299)
                                                                              at android.view.View.performClick(View.java:4084)
                                                                              at android.view.View$PerformClick.run(View.java:16966)
                                                                              at android.os.Handler.handleCallback(Handler.java:615)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                              at android.os.Looper.loop(Looper.java:137)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:511)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                              at dalvik.system.NativeStart.main(Native Method)`

**Comment by julianfalcionelli** [comment]
Hi @JairAviles, I will take a look on that.

Just for case, can you share the code that is causing the crash ?

**Comment by JairAviles** [comment]
Sure, I have defined my form layout in this way. Take into account I am working with widgets from the support library

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/containerForm"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/form_bg"
   >
   
        <LinearLayout
            android:id="@+id/content"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_horizontal"
            android:layout_alignParentTop="true"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:orientation="vertical"
            android:focusable="true"
            android:focusableInTouchMode="true"
            android:weightSum="1">


            <TextView
                android:id="@+id/save_form_description"
                android:layout_height="wrap_content"
                android:layout_width="@dimen/edittext_form_width"
                android:layout_marginTop="@dimen/layout_margin_30dp"
                android:textColor="@android:color/white"
                android:textSize="@dimen/textsize_title_dialog_text"
                android:text="@string/save_person_form_description"
                android:layout_marginBottom="@dimen/layout_margin_10dp"
            />

            <android.support.design.widget.TextInputLayout
                android:id="@+id/text_layout_name"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:gravity="center"
                android:layout_marginTop="@dimen/layout_margin_14dp"
                android:theme="@style/EditTextWhite">

                <android.support.design.widget.TextInputEditText
                    android:id="@+id/edit_text_name"
                    android:layout_width="@dimen/edittext_form_width"
                    android:layout_height="wrap_content"
                    android:hint="@string/name"
                    />

            </android.support.design.widget.TextInputLayout>

            <android.support.design.widget.TextInputLayout
                android:id="@+id/text_layout_email"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:gravity="center"
                android:layout_marginTop="@dimen/layout_margin_14dp"
                android:theme="@style/EditTextWhite">

                <android.support.design.widget.TextInputEditText
                    android:id="@+id/edit_text_email"
                    android:layout_width="@dimen/edittext_form_width"
                    android:layout_height="wrap_content"
                    android:hint="@string/email"
                    android:inputType="textEmailAddress"
                    />

            </android.support.design.widget.TextInputLayout>

            <ImageView
                android:id="@+id/save_form"
                android:src="@drawable/stamp_button"
                android:layout_width="@dimen/stamp_image_form_width"
                android:layout_height="@dimen/stamp_image_form_width"
                android:layout_margin="@dimen/layout_margin_30dp"
                android:layout_gravity="end"
                />

        </LinearLayout>





</RelativeLayout>


My activity overrides the interface methods just as your documentation states.

**Comment by julianfalcionelli** [comment]
@JairAviles I just tested MagicForm in API Lvl = 16 and worked fine, probably that issue is related the Styles/Themes which is not related to this library. 

Maybe the problem is in       
      `android:theme="@style/EditTextWhite">`

Just to be sure, make sure you have the version 1.4 of MagicForm.

**Comment by JairAviles** [comment]
@julianfalcionelli Indeed, I was using custom themes but seems to have a conflict with the MagicForm. Nonetheless, I was able to resolve it about using default Android themes.
